#modloaded mekanism

// Default recipes
// <actuallyadditions:item_dust:3>, <minecraft:emerald>)
// <actuallyadditions:item_dust:4>, <minecraft:dye:4>)
// <actuallyadditions:item_dust:5>, <minecraft:quartz>)
// <actuallyadditions:item_dust:6>, <minecraft:coal>)
// <appliedenergistics2:charged_quartz_ore>, <appliedenergistics2:material:1> * 4)
// <appliedenergistics2:crystal_seed:1200>.withTag({progress: 1600}), <appliedenergistics2:material:12>)
// <appliedenergistics2:crystal_seed:600>.withTag({progress: 1000}), <appliedenergistics2:material:11>)
// <appliedenergistics2:crystal_seed>.withTag({progress: 400}), <appliedenergistics2:material:10>)
// <appliedenergistics2:material:2>, <appliedenergistics2:material:10>)
// <appliedenergistics2:material:3>, <minecraft:quartz>)
// <appliedenergistics2:material:7>, <appliedenergistics2:material:12>)
// <appliedenergistics2:material:8>, <appliedenergistics2:material:12>)
// <appliedenergistics2:material>, <appliedenergistics2:material:10>)
// <appliedenergistics2:quartz_ore>, <appliedenergistics2:material> * 4)
// <bewitchment:amethyst_ore>, <biomesoplenty:gem> * 2)
// <bewitchment:silver_ore>, <thermalfoundation:material:66> * 2)
// <bigreactors:oreyellorite>, <bigreactors:dustyellorium> * 2)
// <biomesoplenty:gem_ore:1>, <biomesoplenty:gem:1> * 2)
// <biomesoplenty:gem_ore:2>, <biomesoplenty:gem:2> * 2)
// <biomesoplenty:gem_ore:3>, <biomesoplenty:gem:3> * 2)
// <biomesoplenty:gem_ore:4>, <biomesoplenty:gem:4> * 2)
// <biomesoplenty:gem_ore:5>, <biomesoplenty:gem:5> * 2)
// <biomesoplenty:gem_ore:6>, <biomesoplenty:gem:6> * 2)
// <biomesoplenty:gem_ore:7>, <biomesoplenty:gem:7> * 2)
// <biomesoplenty:gem_ore>, <biomesoplenty:gem> * 2)
// <bloodmagic:component:21>, <minecraft:coal>)
// <draconicevolution:draconium_ore:1>, <draconicevolution:draconium_dust> * 2)
// <draconicevolution:draconium_ore:2>, <draconicevolution:draconium_dust> * 2)
// <draconicevolution:draconium_ore>, <draconicevolution:draconium_dust> * 2)
// <embers:ore_quartz>, <minecraft:quartz> * 6)
// <enderio:item_material:23>, <minecraft:coal>)
// <enderio:item_material:32>, <minecraft:dye:4>)
// <enderio:item_material:33>, <minecraft:quartz>)
// <erebus:ore_aluminium>, <thermalfoundation:material:68> * 2)
// <erebus:ore_coal>, <minecraft:coal> * 2)
// <erebus:ore_copper>, <thermalfoundation:material:64> * 2)
// <erebus:ore_diamond>, <minecraft:diamond> * 2)
// <erebus:ore_emerald>, <minecraft:emerald> * 2)
// <erebus:ore_encrusted_diamond>, <minecraft:diamond> * 2)
// <erebus:ore_gold>, <thermalfoundation:material:1> * 2)
// <erebus:ore_iron>, <thermalfoundation:material> * 2)
// <erebus:ore_lapis>, <minecraft:dye:4> * 12)
// <erebus:ore_lead>, <thermalfoundation:material:67> * 2)
// <erebus:ore_petrified_quartz>, <minecraft:quartz> * 6)
// <erebus:ore_quartz>, <minecraft:quartz> * 6)
// <erebus:ore_silver>, <thermalfoundation:material:66> * 2)
// <erebus:ore_tin>, <thermalfoundation:material:65> * 2)
// <forestry:resources:1>, <thermalfoundation:material:64> * 2)
// <forestry:resources:2>, <thermalfoundation:material:65> * 2)
// <forestry:resources>, <forestry:apatite> * 4)
// <immersiveengineering:material:24>, <minecraft:gunpowder>)
// <immersiveengineering:material:25>, <minecraft:gunpowder>)
// <immersiveengineering:ore:1>, <thermalfoundation:material:68> * 2)
// <immersiveengineering:ore:2>, <thermalfoundation:material:67> * 2)
// <immersiveengineering:ore:3>, <thermalfoundation:material:66> * 2)
// <immersiveengineering:ore:4>, <thermalfoundation:material:69> * 2)
// <immersiveengineering:ore:5>, <immersiveengineering:metal:14> * 2)
// <immersiveengineering:ore>, <thermalfoundation:material:64> * 2)
// <immersiveintelligence:material_dust:7>, <minecraft:quartz>)
// <immersiveintelligence:material:22> * 8, <minecraft:coal:1>)
// <immersiveintelligence:ore>, <thermalfoundation:material:70> * 2)
// <libvulpes:ore0:10>, <thermalfoundation:material:71> * 2)
// <libvulpes:ore0:4>, <thermalfoundation:material:64> * 2)
// <libvulpes:ore0:5>, <thermalfoundation:material:65> * 2)
// <libvulpes:ore0:9>, <thermalfoundation:material:68> * 2)
// <mekanism:dirtydust:1>, <thermalfoundation:material:1>)
// <mekanism:dirtydust:2>, <mekanism:dust:2>)
// <mekanism:dirtydust:3>, <thermalfoundation:material:64>)
// <mekanism:dirtydust:4>, <thermalfoundation:material:65>)
// <mekanism:dirtydust:5>, <thermalfoundation:material:66>)
// <mekanism:dirtydust:6>, <thermalfoundation:material:67>)
// <mekanism:dirtydust>, <thermalfoundation:material>)
// <mekanism:oreblock:1>, <thermalfoundation:material:64> * 2)
// <mekanism:oreblock:2>, <thermalfoundation:material:65> * 2)
// <mekanism:oreblock>, <mekanism:dust:2> * 2)
// <mekanism:otherdust:3>, <minecraft:gunpowder>)
// <mekanism:otherdust:5>, <mekanism:compressedobsidian>)
// <mekanism:plasticblock:1>, <mekanism:slickplasticblock:1>)
// <mekanism:plasticblock:10>, <mekanism:slickplasticblock:10>)
// <mekanism:plasticblock:11>, <mekanism:slickplasticblock:11>)
// <mekanism:plasticblock:12>, <mekanism:slickplasticblock:12>)
// <mekanism:plasticblock:13>, <mekanism:slickplasticblock:13>)
// <mekanism:plasticblock:14>, <mekanism:slickplasticblock:14>)
// <mekanism:plasticblock:15>, <mekanism:slickplasticblock:15>)
// <mekanism:plasticblock:2>, <mekanism:slickplasticblock:2>)
// <mekanism:plasticblock:3>, <mekanism:slickplasticblock:3>)
// <mekanism:plasticblock:4>, <mekanism:slickplasticblock:4>)
// <mekanism:plasticblock:5>, <mekanism:slickplasticblock:5>)
// <mekanism:plasticblock:6>, <mekanism:slickplasticblock:6>)
// <mekanism:plasticblock:7>, <mekanism:slickplasticblock:7>)
// <mekanism:plasticblock:8>, <mekanism:slickplasticblock:8>)
// <mekanism:plasticblock:9>, <mekanism:slickplasticblock:9>)
// <mekanism:plasticblock>, <mekanism:slickplasticblock>)
// <mekanism:polyethene> * 3, <mekanism:polyethene:2>)
// <mekanism:saltblock>, <mekanism:salt> * 4)
// <mekanism:sawdust> * 8, <minecraft:coal:1>)
// <minecraft:clay>, <minecraft:clay_ball> * 4)
// <minecraft:coal_ore>, <minecraft:coal> * 2)
// <minecraft:coal:1>, <mekanism:compressedcarbon>)
// <minecraft:coal>, <mekanism:compressedcarbon>)
// <minecraft:diamond_ore>, <minecraft:diamond> * 2)
// <minecraft:diamond>, <mekanism:compresseddiamond>)
// <minecraft:emerald_ore>, <minecraft:emerald> * 2)
// <minecraft:glowstone>, <minecraft:glowstone_dust> * 4)
// <minecraft:gold_ore>, <thermalfoundation:material:1> * 2)
// <minecraft:gravel>, <minecraft:cobblestone>)
// <minecraft:gunpowder>, <minecraft:flint>)
// <minecraft:iron_ore>, <thermalfoundation:material> * 2)
// <minecraft:lapis_ore>, <minecraft:dye:4> * 12)
// <minecraft:mossy_cobblestone>, <minecraft:cobblestone>)
// <minecraft:obsidian>, <thermalfoundation:material:770> * 4)
// <minecraft:quartz_ore>, <enderio:item_material:33> * 2)
// <minecraft:redstone_ore>, <minecraft:redstone> * 12)
// <minecraft:redstone>, <mekanism:compressedredstone>)
// <minecraft:sand>, <minecraft:gravel>)
// <minecraft:stone>, <minecraft:stonebrick:2>)
// <minecraft:stonebrick:1>, <minecraft:stonebrick>)
// <minecraft:stonebrick:2>, <minecraft:stonebrick>)
// <minecraft:stonebrick>, <minecraft:stonebrick:3>)
// <mysticalagriculture:end_inferium_ore>, <mysticalagriculture:crafting> * 8)
// <mysticalagriculture:end_prosperity_ore>, <mysticalagriculture:crafting:5> * 8)
// <mysticalagriculture:inferium_ore>, <mysticalagriculture:crafting> * 4)
// <mysticalagriculture:nether_inferium_ore>, <mysticalagriculture:crafting> * 6)
// <mysticalagriculture:nether_prosperity_ore>, <mysticalagriculture:crafting:5> * 6)
// <mysticalagriculture:prosperity_ore>, <mysticalagriculture:crafting:5> * 4)
// <netherendingores:ore_end_modded_1:1>, <thermalfoundation:material:64> * 4)
// <netherendingores:ore_end_modded_1:11>, <mekanism:dust:2> * 4)
// <netherendingores:ore_end_modded_1:12>, <immersiveengineering:metal:14> * 4)
// <netherendingores:ore_end_modded_1:13>, <bigreactors:dustyellorium> * 4)
// <netherendingores:ore_end_modded_1:14>, <libvulpes:productgem> * 4)
// <netherendingores:ore_end_modded_1:15>, <matteroverdrive:tritanium_dust> * 4)
// <netherendingores:ore_end_modded_1:2>, <thermalfoundation:material:71> * 4)
// <netherendingores:ore_end_modded_1:3>, <thermalfoundation:material:67> * 4)
// <netherendingores:ore_end_modded_1:4>, <thermalfoundation:material:72> * 4)
// <netherendingores:ore_end_modded_1:5>, <thermalfoundation:material:69> * 4)
// <netherendingores:ore_end_modded_1:6>, <thermalfoundation:material:70> * 4)
// <netherendingores:ore_end_modded_1:7>, <thermalfoundation:material:66> * 4)
// <netherendingores:ore_end_modded_1:8>, <thermalfoundation:material:65> * 4)
// <netherendingores:ore_end_modded_1>, <thermalfoundation:material:68> * 4)
// <netherendingores:ore_end_modded_2:1>, <biomesoplenty:gem:1> * 4)
// <netherendingores:ore_end_modded_2:2>, <biomesoplenty:gem:6> * 4)
// <netherendingores:ore_end_modded_2:3>, <biomesoplenty:gem:2> * 4)
// <netherendingores:ore_end_modded_2:4>, <projectred-core:resource_item:105> * 4)
// <netherendingores:ore_end_modded_2:5>, <aether:ambrosium_shard> * 4)
// <netherendingores:ore_end_modded_2:7>, <aether:zanite_gemstone> * 4)
// <netherendingores:ore_end_modded_2:9>, <aether:icestone> * 4)
// <netherendingores:ore_end_modded_2>, <qmd:dust:7> * 4)
// <netherendingores:ore_end_vanilla:1>, <minecraft:diamond> * 4)
// <netherendingores:ore_end_vanilla:2>, <minecraft:emerald> * 4)
// <netherendingores:ore_end_vanilla:3>, <thermalfoundation:material:1> * 4)
// <netherendingores:ore_end_vanilla:4>, <thermalfoundation:material> * 4)
// <netherendingores:ore_end_vanilla:5>, <minecraft:dye:4> * 24)
// <netherendingores:ore_end_vanilla:6>, <minecraft:redstone> * 24)
// <netherendingores:ore_end_vanilla>, <minecraft:coal> * 4)
// <netherendingores:ore_nether_modded_1:1>, <thermalfoundation:material:64> * 4)
// <netherendingores:ore_nether_modded_1:11>, <mekanism:dust:2> * 4)
// <netherendingores:ore_nether_modded_1:12>, <immersiveengineering:metal:14> * 4)
// <netherendingores:ore_nether_modded_1:13>, <bigreactors:dustyellorium> * 4)
// <netherendingores:ore_nether_modded_1:14>, <libvulpes:productgem> * 4)
// <netherendingores:ore_nether_modded_1:15>, <matteroverdrive:tritanium_dust> * 4)
// <netherendingores:ore_nether_modded_1:2>, <thermalfoundation:material:71> * 4)
// <netherendingores:ore_nether_modded_1:3>, <thermalfoundation:material:67> * 4)
// <netherendingores:ore_nether_modded_1:4>, <thermalfoundation:material:72> * 4)
// <netherendingores:ore_nether_modded_1:5>, <thermalfoundation:material:69> * 4)
// <netherendingores:ore_nether_modded_1:6>, <thermalfoundation:material:70> * 4)
// <netherendingores:ore_nether_modded_1:7>, <thermalfoundation:material:66> * 4)
// <netherendingores:ore_nether_modded_1:8>, <thermalfoundation:material:65> * 4)
// <netherendingores:ore_nether_modded_1>, <thermalfoundation:material:68> * 4)
// <netherendingores:ore_nether_modded_2:1>, <biomesoplenty:gem:1> * 4)
// <netherendingores:ore_nether_modded_2:2>, <biomesoplenty:gem:6> * 4)
// <netherendingores:ore_nether_modded_2:3>, <biomesoplenty:gem:2> * 4)
// <netherendingores:ore_nether_modded_2:4>, <projectred-core:resource_item:105> * 4)
// <netherendingores:ore_nether_modded_2:5>, <aether:ambrosium_shard> * 4)
// <netherendingores:ore_nether_modded_2:7>, <aether:zanite_gemstone> * 4)
// <netherendingores:ore_nether_modded_2:9>, <aether:icestone> * 4)
// <netherendingores:ore_nether_modded_2>, <qmd:dust:7> * 4)
// <netherendingores:ore_nether_vanilla:1>, <minecraft:diamond> * 4)
// <netherendingores:ore_nether_vanilla:2>, <minecraft:emerald> * 4)
// <netherendingores:ore_nether_vanilla:3>, <thermalfoundation:material:1> * 4)
// <netherendingores:ore_nether_vanilla:4>, <thermalfoundation:material> * 4)
// <netherendingores:ore_nether_vanilla:5>, <minecraft:dye:4> * 24)
// <netherendingores:ore_nether_vanilla:6>, <minecraft:redstone> * 24)
// <netherendingores:ore_nether_vanilla>, <minecraft:coal> * 4)
// <netherendingores:ore_other_1:1>, <minecraft:quartz> * 6)
// <netherendingores:ore_other_1>, <minecraft:quartz> * 6)
// <nuclearcraft:gem_dust:2>, <minecraft:quartz>)
// <nuclearcraft:gem_dust:6>, <minecraft:gunpowder>)
// <nuclearcraft:gem_dust:7>, <minecraft:coal>)
// <nuclearcraft:gem_dust>, <minecraft:diamond>)
// <nuclearcraft:ore:1>, <thermalfoundation:material:65> * 2)
// <nuclearcraft:ore:2>, <thermalfoundation:material:67> * 2)
// <nuclearcraft:ore:4>, <immersiveengineering:metal:14> * 2)
// <nuclearcraft:ore>, <thermalfoundation:material:64> * 2)
// <projectred-exploration:ore:1>, <biomesoplenty:gem:6> * 2)
// <projectred-exploration:ore:2>, <biomesoplenty:gem:2> * 2)
// <projectred-exploration:ore:3>, <thermalfoundation:material:64> * 2)
// <projectred-exploration:ore:4>, <thermalfoundation:material:65> * 2)
// <projectred-exploration:ore:5>, <thermalfoundation:material:66> * 2)
// <projectred-exploration:ore>, <biomesoplenty:gem:1> * 2)
// <qmd:chemical_dust:2>, <minecraft:gunpowder>)
// <soot:sulfur>, <minecraft:gunpowder>)
// <thaumcraft:ore_amber>, <biomesoplenty:gem:7> * 2)
// <thaumcraft:ore_quartz>, <minecraft:quartz> * 6)
// <thermalfoundation:material:768>, <minecraft:coal>)
// <thermalfoundation:material:769>, <minecraft:coal:1>)
// <thermalfoundation:material:771>, <minecraft:gunpowder>)
// <thermalfoundation:material:772>, <minecraft:gunpowder>)
// <thermalfoundation:material:800> * 8, <minecraft:coal:1>)
// <thermalfoundation:ore:1>, <thermalfoundation:material:65> * 2)
// <thermalfoundation:ore:2>, <thermalfoundation:material:66> * 2)
// <thermalfoundation:ore:3>, <thermalfoundation:material:67> * 2)
// <thermalfoundation:ore:4>, <thermalfoundation:material:68> * 2)
// <thermalfoundation:ore:5>, <thermalfoundation:material:69> * 2)
// <thermalfoundation:ore:6>, <thermalfoundation:material:70> * 2)
// <thermalfoundation:ore:7>, <thermalfoundation:material:71> * 2)
// <thermalfoundation:ore:8>, <thermalfoundation:material:72> * 2)
// <thermalfoundation:ore>, <thermalfoundation:material:64> * 2)

// Remove recipes
mods.mekanism.enrichment.removeAllRecipes();

// mods.mekanism.enrichment.addRecipe(IIngredient inputStack, IItemStack outputStack);
mods.mekanism.enrichment.addRecipe(<minecraft:coal>, <mekanism:compressedcarbon>);
mods.mekanism.enrichment.addRecipe(<minecraft:coal:1>, <mekanism:compressedcarbon>);
mods.mekanism.enrichment.addRecipe(<actuallyadditions:item_crystal>, <mekanism:compressedredstone>);
mods.mekanism.enrichment.addRecipe(<actuallyadditions:item_crystal:2>, <mekanism:compresseddiamond>);
mods.mekanism.enrichment.addRecipe(<mekanism:otherdust:5>, <mekanism:compressedobsidian>);
mods.mekanism.enrichment.addRecipe(<minecraft:glowstone>, <minecraft:glowstone_dust> * 4);
mods.mekanism.enrichment.addRecipe(<minecraft:gunpowder>, <minecraft:flint>);

// ore > dust
mods.mekanism.enrichment.addRecipe(<thaumcraft:ore_amber>, <thaumcraft:amber> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:iron_ore>, <thermalfoundation:material> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:gold_ore>, <thermalfoundation:material:1> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:coal_ore>, <thermalfoundation:material:768> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:coal_ore>, <thermalfoundation:material:768> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:obsidian>, <thermalfoundation:material:770> * 4);
mods.mekanism.enrichment.addRecipe(<mekanism:oreblock>, <mekanism:dust:2> * 2); // osmium
mods.mekanism.enrichment.addRecipe(<minecraft:quartz_ore>, <appliedenergistics2:material:3> * 2);
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore>, <thermalfoundation:material:64> * 2); // copper
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:1>, <thermalfoundation:material:65> * 2); // tin
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:2>, <thermalfoundation:material:66> * 2); // silver
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:3>, <thermalfoundation:material:67> * 2); // lead
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:4>, <thermalfoundation:material:68> * 2); // aluminum
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:5>, <thermalfoundation:material:69> * 2); // nickel
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:6>, <thermalfoundation:material:70> * 2); // platinum
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:7>, <thermalfoundation:material:71> * 2); // iridium
mods.mekanism.enrichment.addRecipe(<minecraft:diamond_ore>, <mekanism:otherdust> * 2);
mods.mekanism.enrichment.addRecipe(<minecraft:emerald_ore>, <actuallyadditions:item_dust:3> * 2);
mods.mekanism.enrichment.addRecipe(<actuallyadditions:block_misc:3>, <actuallyadditions:item_dust:7> * 2); // black quartz
mods.mekanism.enrichment.addRecipe(<projectred-exploration:ore>, <projectred-core:resource_item:200> * 2); // ruby
mods.mekanism.enrichment.addRecipe(<projectred-exploration:ore:1>, <projectred-core:resource_item:201> * 2); // sapphire
mods.mekanism.enrichment.addRecipe(<projectred-exploration:ore:2>, <projectred-core:resource_item:202> * 2); // peridot
mods.mekanism.enrichment.addRecipe(<biomesoplenty:gem_ore>, <biomesoplenty:gem> * 2); // ender amethyst
mods.mekanism.enrichment.addRecipe(<nuclearcraft:ore:6>, <nuclearcraft:dust:6> * 2); // lithium
mods.mekanism.enrichment.addRecipe(<nuclearcraft:ore:5>, <nuclearcraft:dust:5> * 2); // boron
// mods.mekanism.enrichment.addRecipe(<nuclearcraft:ore:4>, <nuclearcraft:dust:4> * 2); // uranium
mods.mekanism.enrichment.addRecipe(<minecraft:lapis_ore>, <enderio:item_material:32> * 8);
mods.mekanism.enrichment.addRecipe(<minecraft:redstone_ore>, <minecraft:redstone> * 8);
mods.mekanism.enrichment.addRecipe(<thermalfoundation:ore:8>, <thermalfoundation:material:72> * 2); // mithril

